PracticaAPI/PracticaAPI/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('usuarios.urls', namespace='usuarios')),
    path('api/',include('usuarios.api.urls', namespace='api_usuarios')),
]

PracticaAPI/usuarios/api/urls.py
from django.urls import path
from usuarios.api import views

app_name="api_usuarios"

urlpatterns=[

	path('lista_usuarios/',views.ListUsuariosAPIView.as_view(),name="listAPIView"),
]

PracticaAPI/usuarios/urls.py
from django.urls import path
from usuarios import views
from django.contrib.auth.views import LoginView, logout_then_login
from django.contrib.auth.decorators import login_required

app_name="usuarios"

urlpatterns=[

	path('',login_required(views.listUsuarios.as_view()),name="listaUsuarios"),
	path('accounts/login/',LoginView.as_view(template_name='usuario/login.html'),name="login_view"),
	path('logout/',logout_then_login, name='logout'),
]

PracticaAPI/usuarios/api/models.py
models.py

PracticaAPI/usuarios/models.py
from django.db import models

# Create your models here.

class Usuario(models.Model):
	nombre=models.CharField(max_length=100)
	#Apellido=models.CharField(max_length=250)
	timestap=models.DateTimeField(auto_now_add=True)
	update=models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.nombre

PracticaAPI/usuarios/api/views.py
from rest_framework import generics
from usuarios.api.serializers import UsuarioModelSerializer
from usuarios.models import Usuario


class ListUsuariosAPIView(generics.ListAPIView):
	serializer_class=UsuarioModelSerializer

	def get_queryset(self, *args,**kwargs):
		return Usuario.objects.all()

PracticaAPI/usuarios/views.py
from django.shortcuts import render
from .models import Usuario
from django.views import generic
# Create your views here.

class listUsuarios(generic.ListView):
	template_name="usuario/lista_usuarios.html"
	model=Usuario

PracticaAPI/templates/base.html
{% load staticfiles %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>{% block title %}{% endblock %}</title>


    


  </head>
  <body>
    
      {% include "navbar.html" %}

      {% block content %}

      {% endblock %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    
    
    <script src="//code.jquery.com/jquery-latest.js"></script>
    {% block script %}
      


    {% endblock %}


    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    


  </body>
</html>

PracticaAPI/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
 {% if user.is_authenticated %}
  <a class="navbar-brand" href="#" style="padding: 10px; border: 1px solid;">{{user.username}}</a>
 {% endif %}
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  {% if user.is_authenticated %}
  <a class="navbar-brand" href="{% url 'usuarios:logout' %}" style="padding: 10px; border: 1px solid;">Cerrar Sesion</a>
  {% endif %}

</nav>

PracticaAPI/templates/usuario/lista_usuarios.html
{% extends "base.html" %}

{% block title %}Lista Usuarios{% endblock %}


{% block script %}
<script type="text/javascript">
		
	$(document).ready(function(){
		console.log("FUNCIONA")
	$.ajax({
			url: "/api/lista_usuarios/",
			method: "GET",
			success: function(data){
				//console.log(data)
				$.each(data,function(key,value){
					console.log(value)
					//var tweetKey=key
					var tweetUser=value.nombre
					var tweetContent = value.timestap
					$("#tweet-container").append("<li>"+tweetUser+"<br>"+tweetContent+"</li>")


				})
			},
			error: function(data){
				console.log("error")
				console.log(data)
			}

		})	
	});	

</script>
{% endblock %}



{% block content %}

<div style="margin-top: 50px;">
	<ul id="tweet-container">
		
	</ul>
        
</div>

{% endblock %}

PracticaAPI/templates/usuario/login.html
{% extends "base.html" %}

{% block content %}


<div class="container" style="margin-top: 40px; box-shadow: #999 0px 10px 10px; padding: 10px; width: ">
<h1>INICIO DE SESION</h1>


<form method="POST">
{% csrf_token %}

	<p><input class="form-control" type="text" name="username" placeholder="Username"></p>
	<p><input class="form-control" type="password" name="password" placeholder="Password"></p>
	
	<input type="submit" value="LOGIN">
	
</form>

</div>
{% endblock %}